=== Nerea1209/Lenguaje-de-Marcas/XML/datos_personales/datos_personales.dtd
<!ELEMENT datos (persona+)>
<!ELEMENT persona (nombre, direccion, (edad|anyo_nac))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT anyo_nac (#PCDATA)>

=== Nerea1209/Lenguaje-de-Marcas/XML/datos_personales/datos_personales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datos SYSTEM "datos_personales.dtd">
<datos>
	<persona>
		<nombre>Nerea</nombre>
		<direccion>Pje. Fray Luís de León nº98</direccion>
		<edad>19</edad>
	</persona>
	<persona>
		<nombre>Juan</nombre>
		<direccion>Avenida Andalucía</direccion>
		<edad>35</edad>
	</persona>
</datos>
