=== Nerea1209/Lenguaje-de-Marcas/XML/Examen_DTD/examen.dtd
<!ELEMENT biblioteca (libros,autores,editoriales)>
<!-- Libros -->
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, precio, fecha_publicacion, revisiones)>
<!ATTLIST libro isbn ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda (euro) #REQUIRED>
<!ELEMENT fecha_publicacion (#PCDATA)>
<!ATTLIST libro escritores IDREFS #REQUIRED>
<!ATTLIST libro id_editorial IDREF #REQUIRED>
<!ELEMENT revisiones (revision+)>
<!ELEMENT revision (valoracion, comentario?)>
<!ATTLIST revision revisor IDREFS #REQUIRED>
<!ELEMENT valoracion (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>
<!-- Autores -->
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre, apellidos, email)>
<!ATTLIST autor nif ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!-- Editoriales -->
<!ELEMENT editoriales (editorial+)>
<!ELEMENT editorial (oficina, web)>
<!ATTLIST editorial nombre_editorial ID #REQUIRED>
<!ELEMENT oficina (#PCDATA)>
<!ELEMENT web (#PCDATA)>

=== Nerea1209/Lenguaje-de-Marcas/XML/Examen_DTD/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "examen.dtd">
<biblioteca>
    <libros>
        <libro isbn="_1-55655-767-6" escritores="_23456788P _23456787G" id_editorial="McGraw-Hill">
            <titulo>Fundamentos de bases de datos</titulo>
            <precio moneda="euro">40</precio>
            <fecha_publicacion>2003</fecha_publicacion>
            <revisiones>
                <revision revisor="_23456789N">
                    <valoracion>8.5</valoracion>
                    <comentario>Es un libro de texto básico</comentario>
                </revision>
            </revisiones>
        </libro>
        <libro isbn="_123456789" escritores="_23456788P _12345678E" id_editorial="Anaya">
            <titulo>Matemáticas 1</titulo>
            <precio moneda="euro">35</precio>
            <fecha_publicacion>1996</fecha_publicacion>
            <revisiones>
                <revision revisor="_23456788P">
                    <valoracion>5</valoracion>
                    <comentario>Tiene muchos problemas</comentario>
                </revision>
            </revisiones>
        </libro>
        <libro isbn="_987654321" escritores="_12345678E" id_editorial="Edi3">
            <titulo>Romeo y Julieta</titulo>
            <precio moneda="euro">67</precio>
            <fecha_publicacion>1963</fecha_publicacion>
            <revisiones>
                <revision revisor="_23456788P">
                    <valoracion>9</valoracion>
                    <comentario>Una historia de amor preciosa</comentario>
                </revision>
                <revision revisor="_23456787G">
                    <valoracion>6</valoracion>
                </revision>
                <revision revisor="_12345678E">
                    <valoracion>8</valoracion>
                    <comentario>Me encanta</comentario>
                </revision>
            </revisiones>
        </libro>
    </libros>
    <autores>
        <autor nif="_23456788P">
            <nombre>Abraham</nombre>
            <apellidos>Silberschatz</apellidos>
            <email>silbers@hotmail.com</email>
        </autor>
        <autor nif="_23456787G">
            <nombre>Henry</nombre>
            <apellidos>Korth</apellidos>
            <email>korth@hotmail.com</email>
        </autor>
        <autor nif="_23456789N">
            <nombre>James</nombre>
            <apellidos>Smith</apellidos>
            <email></email>
        </autor>
        <autor nif="_12345678E">
            <nombre>Williams</nombre>
            <apellidos>Shakespeare</apellidos>
            <email>willy@gmail.com</email>
        </autor>
    </autores>
    <editoriales>
        <editorial nombre_editorial="McGraw-Hill">
            <oficina>Av. Santander s/n</oficina>
            <web>http://www.mcgrawhill.es.</web>
        </editorial>
        <editorial nombre_editorial="Anaya">
            <oficina>Av. Andalucia 44</oficina>
            <web>http://www.anaya.es.</web>
        </editorial>
        <editorial nombre_editorial="Edi3">
            <oficina>Calle Ruben Darío 7</oficina>
            <web>http://www.edi3.es.</web>
        </editorial>
    </editoriales>
</biblioteca>
