=== Nerea1209/Lenguaje-de-Marcas/XML/ejerciciosFinales/banco_lorca.dtd
<!ELEMENT banco (sucursal*)>
<!ELEMENT sucursal (cuentaCorriente*)>
<!ATTLIST sucursal id ID #REQUIRED>
<!ELEMENT cuentaCorriente (cliente+, domiciliaciones?)>
<!ATTLIST cuentaCorriente id ID #REQUIRED>
<!ELEMENT cliente (privilegios, prestamos?)>
<!ATTLIST cliente nif CDATA #REQUIRED>
<!ELEMENT privilegios (#PCDATA)>
<!ELEMENT prestamos (prestamo+)>
<!ELEMENT prestamo (#PCDATA)>
<!ELEMENT domiciliaciones (#PCDATA)>

=== Nerea1209/Lenguaje-de-Marcas/XML/ejerciciosFinales/banco_lorca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco SYSTEM "banco_lorca.dtd">
<banco>
    <sucursal id="sucursal1">
        <cuentaCorriente id="c1">
            <cliente nif="165494531c">
                <privilegios>Titular</privilegios>
                <prestamos>
                    <prestamo>5842.355â‚¬</prestamo>
                </prestamos>
            </cliente>
            <cliente nif="654894894h">
                <privilegios>No titular</privilegios>
            </cliente>
        </cuentaCorriente>
        <cuentaCorriente id="c2">
            <cliente nif="5988546j">
                <privilegios>Titular</privilegios>
            </cliente>
            <domiciliaciones>sfjkd</domiciliaciones>
        </cuentaCorriente>

    </sucursal>
</banco>
