=== Nerea1209/Lenguaje-de-Marcas/XML/ejerciciosFinales/Buzon_correos.dtd
<!ELEMENT buzon_correos (cartas, paquetes)>
<!ELEMENT cartas (carta*)>
<!ELEMENT carta (destinatario)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT paquetes (paquete*)>
<!ELEMENT paquete (destinatario)>

=== Nerea1209/Lenguaje-de-Marcas/XML/ejerciciosFinales/Buzon_correos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE buzon_correos SYSTEM "Buzon_correos.dtd">
<buzon_correos>
    <cartas>
        <carta>
            <destinatario>Pepe</destinatario>
        </carta>
        <carta>
            <destinatario>Luc√≠a</destinatario>
        </carta>
    </cartas>
    <paquetes>
        <paquete>
            <destinatario>Eduardo</destinatario>
        </paquete>
    </paquetes>
</buzon_correos>
