=== Nerea1209/Lenguaje-de-Marcas/XML/ejerciciosFinales/MOTORSOL.dtd
<!ELEMENT motorsol (motor*)>
<!ELEMENT motor (piezas, tipo)>
<!ELEMENT piezas (pieza+)>
<!ELEMENT pieza (#PCDATA)>
<!ELEMENT tipo (fabricado_por, empleados)>
<!ELEMENT fabricado_por (#PCDATA)>
<!ELEMENT empleados (responsable, empleado+)>
<!ELEMENT responsable (nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT empleado (nombre, cargoFamiliar?)>
<!ELEMENT cargoFamiliar (familiar+)>
<!ELEMENT familiar (nombre)>

=== Nerea1209/Lenguaje-de-Marcas/XML/ejerciciosFinales/MOTORSOL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE motorsol SYSTEM "MOTORSOL.dtd">
<motorsol>
    <motor>
        <piezas>
            <pieza>sakdhsiouhf</pieza>
        </piezas>
        <tipo>
            <fabricado_por>sdfsdf</fabricado_por>
            <empleados>
                <responsable>
                    <nombre>fsdfdf</nombre>
                </responsable>
                <empleado>
                    <nombre>jujbu</nombre>
                    <cargoFamiliar>
                        <familiar>
                            <nombre>kehgoiehrg</nombre>
                        </familiar>
                    </cargoFamiliar>
                </empleado>
            </empleados>
        </tipo>
    </motor>
</motorsol>
